$('.owl-carousel').owlCarousel({
    loop:true,
    margin:15,
    nav:false,
    responsive:{
        0:{
            items:1
        },
        200:{
            items:2
        },
        400:{
            items:3
        },
        600:{
            items:4   
        },
        800:{
            items:5
        },
        1000:{
            items:6
        }
    }
})